config/routes.rb
Rails.application.routes.draw do
  # get 'bookings/create'
  # get 'cars/index'
  # get 'cars/show'
  devise_for :users
  resources :cars, only: %i[destroy]
  root to: "pages#home"

  get 'my_cars', to: 'cars#my_cars'

  resources :cars do
    resources :bookings, only: %i[new create destroy]

    collection do
      get :search
    end

    resources :bookings, only: %i[new create destroy]
  end

  resources :bookings, except: %i[new index create]

  get '/bookings', to: 'bookings#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car

  validates :starts_at, :ends_at, presence: true
  validates :total_price, presence: true
  # before_destroy :destroy_user_bookings
  before_save :calculate_total_price

  private

  # def destroy_user_bookings
  #   Booking.where(user_id: user_id).destroy_all
  # end

  def calculate_total_price
    self.total_price = (ends_at - starts_at).to_i * car.price_per_day
  end
end

app/models/car.rb
class Car < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  belongs_to :user

  has_many :bookings
  has_one_attached :photo

  validates :brand, presence: true
  validates :model, presence: true
  validates :year_of_production, presence: true
  validates :address, presence: true

  validates :price_per_day, numericality: { greater_than: 0 }

  include PgSearch::Model
  pg_search_scope :search_by_city_address, against: [ :address ], using: {
    tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true
  has_many :cars
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :set_booking, only: %i[show destroy]
  before_action :set_car, only: %i[new create]

  def index
    @bookings = Booking.all
    @my_bookings = Booking.where(user_id: current_user.id)
  end

  def new
    @booking = Booking.new
    @car = Car.find(params[:car_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user_id = @user.id
    @booking.car_id = @car.id
    @booking.total_price = ((@booking.ends_at - @booking.starts_at).to_i) * @car.price_per_day
    if @booking.save
      redirect_to @car, notice: "Votre réservation a été créée avec succès."
    else
      render :new
    end
  end

  def destroy
    @booking.destroy
    redirect_to booking_path(@car, @booking)

  end


  private

  def set_car
    @car = Car.find(params[:car_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_user
    @user = current_user
  end

  def booking_params
    params.require(:booking).permit(:starts_at, :ends_at)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :find_user, :database_search
  before_action :find_car, only: %i[show edit update destroy]

  def index
    @cars = Car.all
    if params[:query].present?
      @cars = Car.search_by_city_and_address(params[:query])
    else
      @cars = Car.all
    end
      @markers = @cars.geocoded.map do |car|
      {
        lat: car.latitude,
        lng: car.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { car: car }),
        marker_html: render_to_string(partial: "marker", locals: {car: car})
      }
    end
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car = current_user.cars.build(car_params)
    if @car.save
      flash[:notice] = "Voiture mise en vente avec succès !"
      redirect_to @car
    else
      flash[:alert] = "Échec de la mise en vente de la voiture. Veuillez réessayer."
      render :new
    end
  end

  def show
    @car = Car.find(params[:id])
    @booking = Booking.new
  end

  def update
    @car.update(car_params)
    @booking = @car.bookings.find(params[:booking_id])
    redirect_to car_path(@car)
  end

  def destroy
    @car.bookings.destroy_all
    @car.destroy
    redirect_to my_cars_path
  end

  def my_cars
    @cars = current_user.cars
    @bookings = @cars.map {|p| p.bookings}.flatten
  end

  def search
    if params[:query].present?
      @cars = Car.search_by_city_address(params[:query])
    else
      @cars = Car.all
    end
    @count = @cars.count
    @query = params[:query]

    @markers = @cars.geocoded.map do |car|
      {
        lat: car.latitude,
        lng: car.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { car: car }),
        marker_html: render_to_string(partial: "marker", locals: {car: car})
      }
    end
  end

  private

  def find_user
    @user = current_user
  end

  def find_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:brand, :model, :address, :year_of_production, :price_per_day, :photo)
  end

  def database_search
    @markers = Car.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/index.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
    <h1 class="display-1">Vos réservations</h1>
  </div>
</div>

<div class="container">
  <div class="row">
    <% @my_bookings.each do |booking| %>
      <% car = Car.find(booking.car_id) %>
      <div class="col-md-4">
        <div class="card-large mb-2">
          <div class="card-block p-3">
            <% if car.photo.key.present? %>
              <%= cl_image_tag booking.car.photo.key, crop: :fill, class:"car_pic card-img-top" %>
            <% else %>
              <%= image_tag("unknown.jpg", class:"car_pic card-img-top") %>
            <% end %>
            <p class="card-title" style="font-size: 26px;">Address: <%= car.address %></p>
            <p class="card-title" style="font-size: 26px;"><span class="font-weight-bold">Model:</span> <%= car.model %></p><br>
            <p class="card-title" style="font-size: 26px;"><span class="font-weight-bold">Prix ​​total:</span> <%= booking.total_price %> Euros</p>

            <div class="d-flex justify-content-center">
              <%= link_to 'Verifier ma location', booking, class: "btn btn-outline-warning btn-lg p-2" %> <br>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="text-center">
      <%= link_to "Retour aux vehicules", cars_path, class:"btn btn-outline-primary btn-lg mb-5" %>
    </div>
  </div>
</div>
  <br>
  <br>

app/views/bookings/new.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
    <h3 class="display-1 pt-5">Faire une réservation pour <%= @car.brand %></h3>
  </div>
</div>

<div class="container d-flex flex-column p-4 mb-4 shadow w-40 mx-auto rental_form">
  <p class="card-text text-center">Réserver le model: <strong><%= @car.model %></strong></p>
  <div class="row card-text">
    <%= simple_form_for [ @car, @booking ] do |f| %>
      <%= f.input  :starts_at, required: false, label: 'Date de début souhaitée', as: :date, html5: true, order: [:day, :month, :year] %>
      <%= f.input :ends_at, required: false, label: 'Date de fin souhaitée', as: :date, html5: true, order: [:day, :month, :year]  %>
      <div class="text-center">
        <%= f.submit "Réserver", class: "btn btn-outline-primary btn-lg w-50" %><br><hr>
        <%= link_to "Retour aux vehicules", cars_path, class: "btn btn-outline-primary btn-lg"  %>
        <%= link_to "Retour à vos réservation", bookings_path(@booking), class: "btn btn-outline-primary btn-lg"  %>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
<% car = Car.find(@booking .car_id) %>
   <h2 class="display-1 pt-5">Votre reservation pour <%= car.brand %></h2>
  </div>
</div>

<div class="container mb-5">
  <div class="row booking_container">
    <div class="col-4">
      <% if car.photo.key.present? %>
        <%= cl_image_tag car.photo.key, crop: :fill, class:"booking_car_pic mx-auto" %>
      <% else %>
        <%= image_tag("unknown.jpg", class:"booking_car_pic mx-auto") %>
      <% end %>
    </div>
    <div class="show_booking col-6">
      <p style="font-size: 26px;"><span class="font-weight-bold">Marque: </span><%= car.brand  %></p>
      <p style="font-size: 26px;"><span class="font-weight-bold">Modél: </span><%= car.model  %></p>
      <p style="font-size: 26px;"><span class="font-weight-bold">A partir de: </span><%= @booking.starts_at.strftime("%e-%m-%Y")  %></p>
      <p style="font-size: 26px;"><span class="font-weight-bold">Jusqu'au: </span><%= @booking.ends_at.strftime("%e-%m-%Y")  %></p>
      <p style="font-size: 26px;"><span class="font-weight-bold">Addresse: </span><%= car.address  %></p>
      <p style="font-size: 26px;"><span class="font-weight-bold">Total Price: </span><%= @booking.total_price %> Euros.</p>
    <%= link_to 'Retour à vos réservations', bookings_path, class: "btn btn-warning btn-lg mb-2" %>
    </div>
  </div>
</div>

app/views/cars/_info_window.html.erb
<%= link_to car do %>
  <% if car.photo.key.nil? %>
    <%= image_tag "no-image.png", class:"img-fluid width: 50% height: auto" %>
  <% else %>
    <%= cl_image_tag car.photo.key, crop: :fill, class:"img-fluid width: 50% height: auto" %>
  <% end %>
  <div class="map-card">
    <p><span class="font-weight-bold" ><i class="fa fa-user"></i></span>  <%= car.brand %></p>
    <p><span class="font-weight-bold"><%= car.price_per_day %>€/Jour </span></p>
  </div>
<% end %>

app/views/cars/_marker.html.erb
<%= image_tag "logo.png", height: 40, width: 40, alt: "Logo" %>

app/views/cars/edit.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
   <h1 class="display-1 pt-5">Ajouter un produits</h1>
  </div>
</div>
<div class="container mb-5">
  <div class="rental_form p-4">
    <%= simple_form_for [ @car ] do |f| %>
      <%= f.input :brand, required: false, label: 'Marque' %>
      <%= f.input :model, required: false, label: 'Modél' %>
      <%= f.input :address, required: false, label: 'Addresse' %>
      <%= f.input :price_per_day, required: false, label: 'Prix par jour' %>
      <%= f.input :year_of_production, required: false, label: 'Anée de production' %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Modifier", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/cars/index.html.erb
<div class="cover mb-4 w-20 p-3 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
    <h1 class="display-1 pt-5">Voitures disponibles</h1>
  </div>
</div>

<div class="cars-map-grid">
    <div id='map' style='width: 80%;'
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  <div class="widget-list row row-cols-3">
    <div class="car-cards p-4">
      <% @cars.each do |car| %>
        <div class="shadow card mb-3 widget">
          <div class="card-block p-3">
            <div class="card-body">
              <% if car.photo.attached? %>
                <%= cl_image_tag car.photo.key, class: 'car_pic card-img-top' %>
              <% else %>
              <%= image_tag("unknown.jpg", class:"car_pic card-img-top") %>
              <% end %>
              <h5 class="card-title"><%= link_to car.brand, car_path(car) %></h5>
              <p class="card-text "><%= car.price_per_day %> €/ jour</p>
              <%= link_to "Fiche détails", car, class:"btn btn-warning btn-lg mb-4" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cars/my_cars.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
    <h1 class="display-1">Mes voitures</h1>
  </div>
</div>
<div class="card-wrapper">
  <div class="my_cars_container p-4">
    <div class="widget-list row row-cols-3">
      <% unless current_user.cars.nil? %>
        <% @cars.each do |car|%>
          <div class="shadow card mb-3 widget">
            <div class="card-header bg-transparent " >
              <ul class="list-inline">
                <li class="list-inline-item">
                <%= link_to car.brand, car_path(car) %>
                </li>
                <li class="list-inline-item">
                <%= button_to'╳', car_path(car), method: :delete, data: {turbo_method: :delete}, class:"button" %>
                </li>
              </ul>
            </div>
              <div class="card-body">
                <% if car.photo.key.present? %>
                <%= cl_image_tag(car.photo.key, class:"") %>
                <% else %>
                  <%= image_tag("unknown.jpg", class:"") %>
                <% end %>
                <p><%= car.address %></p>
              </div>
            <div class="card-footer bg-transparent">
              <%= link_to 'Modifier', edit_car_path(car), class:"" %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/cars/new.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
    <h1 class="display-1 pt-5">Ajouter une voiture</h1>
  </div>
</div>

<div class="container p-5">
  <div class="rental_form shadow p-4">
    <%= simple_form_for [ @car ] do |f| %>
      <%= f.input :brand, required: false, label: 'Marque' %>
      <%= f.input :model, required: false, label: 'Modél' %>
      <%= f.input :address, required: false, label: 'Addresse' %>
      <%= f.input :price_per_day, required: false, label: 'Prix par jour' %>
      <%= f.input :year_of_production, required: false, label: 'Anée de production' %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Ajouter", class: "btn btn-outline-primary btn-lg mb-5" %>
    <% end %>
  </div>
</div>

app/views/cars/search.html.erb
<% @search_colon = @query.present? ? ":" : ""  %>
<% @search_text =  @count > 1 || @count == 0 ? "cars" : "car" %>
<h1 class="text-center">All Available cars</h1>
<h3 class="text-center"><%= @query&.capitalize %> <%= @search_colon %> <%= @count %> <%=@search_text %> found </h3>
<div class="px-5 cars-map-grid">
    <div id='map' style='width: 100%;'
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  <div class="car-cards">
    <% @cars.each do |car| %>
    <div>
      <div class="card mb-2">
        <div class="card-block p-3">
          <div class="cars-photo">
            <% if car.photo.key.present? %>
              <%= cl_image_tag car.photo.key, class:"card-img-top search-image " %>
            <% else %>
            <%= image_tag("unknown.jpg", class:"card-img-top search-image") %>
            <% end %>
          </div>
          <strong><p class="card-title"><%= car.address %></p></strong>
          <p class="card-subtitle text-muted"><span class="font-weight-bold">Price:</span> <%= car.price_per_day %> Euros</p>
            <%= link_to 'Check it out!', car, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
<h1><%= link_to "Go back to home page", root_path, class: "btn btn-primary" %></h1>

app/views/cars/show.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
   <h1 class="display-1 "><%= @car.brand %></h1>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <% if @car.photo.attached? %>
          <%= cl_image_tag @car.photo.key, class: 'car_pic' %>
      <% end %>
    </div>
    <div class="col-md-4">
      <div class="card-body">
        <h1 class="card-text">Marque: <%= @car.brand %></h1><br>
        <p style="font-size: 20px;">Modél: <%= @car.model %></p><br>
        <p style="font-size: 20px;">Année de production: <%= @car.year_of_production %></p><br>
        <p style="font-size: 20px;">Adresse: <%= @car.address %></p><br>
        <p style="font-size: 20px;">Prix: <%= @car.price_per_day %>€/jour </p>
      </div>
    </div>
  </div>
</div>

<div class="text-decoration-none text-center">
    <%= link_to "Réserver", "/cars/#{params[:id]}/bookings/new", class: "btn btn-outline-primary btn-lg" %>
    <%= link_to "Retour aux vehicules", cars_path, class: "btn btn-outline-primary btn-lg" %>
</div>
<br>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRentCarsChallenge</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src='https://api.mapbox.com/mapbox-gl-js/v2.12.0/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.12.0/mapbox-gl.css' rel='stylesheet' />

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div id="app">
    <div class="title">
      <div class="title-inner">
        <div class="cafe">
          <div class="cafe-inner">LOCA DRIVE</div>
        </div>
        <div class="mozart">
          <div class="mozart-inner" ><%= link_to "Découvrez notre gamme", cars_path, class:"btn btn-outline-dark btn-lg" %></div>
        </div>
      </div>
    </div>

    <div class="image">
      <%= image_tag 'banner.jpg' %>
    </div>
  </div>

  <script src="https://codepen.io/shshaw/pen/QmZYMG.js"></script>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-lg navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png", class:"logo" %>
    <% end %>

    <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <%# <h1 data-text= "Spotlight">LOCA 🚙 DRIVE</h1> %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav me-auto link_list">
        <li class="nav-item active">
          <%= link_to "ACCUEIL /", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "VEHICULES /", cars_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "MES RESERVATIONS /", bookings_path(@booking), class: "nav-link" %>
        </li>

          <li class="nav-item dropdown menu">
            <%= image_tag "sign_in.png", class: "avatar-large dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

            <div class="dropdown-menu dropdown-menu-end link_list" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Profil - <%= current_user.email %></a>
              <%= link_to "Mes voitures", my_cars_path, class: "dropdown-item" %>
              <%= link_to "Ajouter une voiture", new_car_path, class: "dropdown-item" %>
              <%= link_to "Mes réservations", bookings_path, class: "dropdown-item" %>
              <%= link_to "Se déconnecter", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
          <% else %>
            <li class="nav-item dropdown">
              <%= link_to "CONNEXION", new_user_session_path, class:"nav-link" %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>